# Generated by Django 5.2.8 on 2025-12-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='color_fondo',
            field=models.CharField(choices=[('bg-green-600', 'Verde (Principal)'), ('bg-amber-600', 'Ámbar (Empanada)'), ('bg-red-600', 'Rojo (Oferta)'), ('bg-blue-600', 'Azul (Novedad)'), ('bg-gray-100', 'Gris Claro (Neutro)')], default='bg-green-600', help_text='Clase de Tailwind. SOLO se permiten las clases de la lista.', max_length=50, verbose_name='Color de Fondo'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='color_texto',
            field=models.CharField(choices=[('text-white', 'Blanco'), ('text-gray-800', 'Gris Oscuro'), ('text-green-900', 'Verde Oscuro')], default='text-white', max_length=50, verbose_name='Color de Texto'),
        ),
    ]
